workspace = { members = [ "tc_cli","tc_core"] }
[package]
name = "tailcall"
version = "0.1.0"
edition = "2021"
resolver = "2"

[[bin]]
name = "tailcall"
path = "tc_cli/src/main.rs"

[dependencies]
tc_cli = {path = "tc_cli"}
tc_core = {path = "tc_core"}

# need these as we set bin path to tc_cli/src/main.rs
exitcode = "1.1.2"
anyhow = "1.0.77"
mimalloc = { version = "0.1.39", default-features = false }


[dev-dependencies]
criterion = "0.5.1"
pretty_assertions = "1.4.0"
stripmargin = "0.1.1"
derive_setters = "0.1.6"
thiserror = "1.0.52"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_urlencoded = "0.7.1"
url = { version = "2", features = ["serde"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = [
    "json",
    "rustls-tls"
], default-features = false }
hyper = { version = "0.14", features = ["full"], default-features = false }
async-graphql = { version = "6.0.11", features = [
    "dynamic-schema",
    "dataloader",
    "apollo_tracing"
] }
async-graphql-value = "6.0.11"
base64 = "0.21"
indexmap = "2.1"
once_cell = "1.19.0"
clap = { version = "4.4.12", features = ["derive"] }
colored = "2"
regex = "1.10.2"
http-cache-reqwest = { version = "0.12.0", features = [
    "manager-moka"
], default-features = false }
reqwest-middleware = "0.2.4"
async-trait = "0.1.75"
serde_path_to_error = "0.1.14"
moka = { version = "0.12.2", default-features = false, features = ["future"] }
cache_control = "0.2.0"
nom = "7.1.3"
resource = "0.5.0"
inquire = "0.6.2"
log = "0.4.20"
env_logger = "0.10.1"
ring = "0.17.7"
num_cpus = "1.16.0"
hyper-rustls = "0.24.2"
rustls = "0.21.9"
rustls-pemfile = "1.0.4"
fnv = "1.0.7"
futures-channel = { version = "0.3.30" }
futures-timer = { version = "3.0.2" }
futures-util = { version = "0.3.30" }
lru = { version = "0.12.1" }
webbrowser = { version = "0.8.12", features = ["hardened", "disable-wsl"] }
ttl_cache = "0.5.1"
protox = "0.5.1"
prost-reflect = { version = "0.12.0", features = ["serde"] }
prost = "0.12.3"


[profile.release]
opt-level = 3
codegen-units = 1
panic = 'abort'
lto = 'thin'
debug = false
incremental = false
overflow-checks = false

[[bench]]
name = "json_like_bench"
harness = false

[[bench]]
name = "request_template_bench"
harness = false

[[bench]]
name = "data_loader_bench"
harness = false

[[bench]]
name = "impl_path_string_for_evaluation_context"
harness = false
