[package]
name = "tailcall"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tailcall"
path = "src/main.rs"

[dependencies]
# the dependencies that might cause error in wasm (workers workspace) must contain optional = true and
# should be added to default feature below.
# it would be nice to keep dependencies seperate, the dependencies specific to tailcall (and not wasm)
# should be placed here:
mimalloc = { version = "0.1.39", default-features = false, optional = true}
http-cache-reqwest = { version = "0.12.0", features = ["manager-moka"], default-features = false, optional = true }
moka = { version = "0.12.1", default-features = false, features = ["future"], optional = true }
hyper-rustls = {version = "0.24.2", optional = true}
rustls = {version = "0.21.9",optional = true}
rustls-pemfile = {version = "1.0.4",optional = true}
inquire = {version = "0.6.2",optional = true}
prettytable-rs = "0.10"

#safe for workers workspace.
http-cache-semantics = "2.0.1"
hyper = { version = "0.14", features = ["server"], default-features = false    }
tokio = { version = "1.35.0", features = ["rt","time"] }
anyhow = "1.0.76"
derive_setters = "0.1.6"
thiserror = "1.0.50"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_urlencoded = "0.7.1"
url = { version = "2", features = ["serde"] }
reqwest = { version = "0.11", features = [
   "json",
   "rustls-tls"
], default-features = false }
async-graphql = { version = "6.0.11", features = ["dynamic-schema", "dataloader", "apollo_tracing"] }
async-graphql-value = "6.0.11"
indexmap = "2.1"
once_cell = "1.19.0"
mini-v8 = { version = "0.4.1", optional = true }
clap = { version = "4.4.11", features = ["derive"] }
colored = "2"
regex = "1.10.2"
reqwest-middleware = "0.2.4"
async-trait = "0.1.75"
serde_path_to_error = "0.1.14"
cache_control = "0.2.0"
nom = "7.1.3"
exitcode = "1.1.2"
resource = "0.5.0"
log = "0.4.20"
env_logger = "0.10.1"
stripmargin = "0.1.1"
num_cpus = "1.16.0"
fnv = "1.0.7"
futures-channel = { version = "0.3.29" }
futures-timer = { version = "3.0.2" }
futures-util = { version = "0.3.29" }
lru = { version = "0.12.1" }
webbrowser = { version = "0.8.12", features = ["hardened", "disable-wsl"] }
async-std = {version = "1.12.0",features = ["wasm-bindgen-futures", "unstable"]}
worker = "0.0.18"
chrono = { version = "0.4.31", features = ["wasmbind"] }
http = "1.0.0"
lazy_static = "1.4.0"
wasm-timer = "0.2.5"

[dev-dependencies]
criterion = "0.5.1"
httpmock = "0.6"
pretty_assertions = "1.4.0"
stripmargin = "0.1.1"

[workspace]
members = [
   ".",
   "workers"
]

[profile.release]
opt-level = 3
codegen-units = 1
panic = 'abort'
lto = 'thin'
debug = false
incremental = false
overflow-checks = false

[features]
unsafe-js = ["dep:mini-v8"]
default = ["tokio/fs", "tokio/rt-multi-thread", "mimalloc", "http-cache-reqwest","moka", "hyper-rustls", "rustls", "rustls-pemfile","inquire"]

[[bench]]
name = "json_like_bench"
harness = false

[[bench]]
name = "request_template_bench"
harness = false

[[bench]]
name = "data_loader_bench"
harness = false

[[bench]]
name = "impl_path_string_for_evaluation_context"
harness = false
