[package]
name = "tailcall"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tailcall"
path = "src/main.rs"

[dependencies]
tc_core = {path = "tc_core" }
cli = {path = "tc_cli" }
mini-v8 = { version = "0.4.1", optional = true }
anyhow = "1.0.76"
exitcode = "1.1.2"
mimalloc = { version = "0.1.39", default-features = false }

[dev-dependencies]
criterion = "0.5.1"
httpmock = "0.6"
pretty_assertions = "1.4.0"
stripmargin = "0.1.1"

# deps required for tests
async-graphql = { version = "6.0.11", features = ["dynamic-schema", "dataloader", "apollo_tracing"] }
derive_setters = "0.1.6"
regex = "1.10.2"
hyper = { version = "0.14", features = ["server"], default-features = false }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
env_logger = "0.10.1"
log = "0.4.20"
tokio = {version = "1.35.1",features = ["full"]}
async-graphql-value = "6.0.11"
url = "2"
reqwest = { version = "0.11", features = [
    "json",
    "rustls-tls"
], default-features = false }
async-trait = "0.1.75"

[workspace]
members = [
    ".",
    "tc_core",
    "tc_cli",
    "tc_cloudflare"
]

[profile.release]
opt-level = 3
codegen-units = 1
panic = 'abort'
lto = 'thin'
debug = false
incremental = false
overflow-checks = false

[features]
unsafe-js = ["dep:mini-v8"]

[[bench]]
name = "json_like_bench"
harness = false

[[bench]]
name = "request_template_bench"
harness = false

[[bench]]
name = "data_loader_bench"
harness = false

[[bench]]
name = "impl_path_string_for_evaluation_context"
harness = false
